<?php
/**
 * @file
 * Custom functionality to add email addresses to the CLO
 */

/**
 * Sets default placeholder text.
 */
define('DEFAULT_PLACEHOLDER_TEXT', 'Your email address');

/**
 * Implements hook_block_info().
 */
function convio_signup_block_info() {
  $blocks['Convio Email Signup'] = array(
    'info' => t('Convio Email Signup'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function convio_signup_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'Convio Email Signup':
      $block['subject'] = NULL;
      $block['content'] = drupal_get_form('convio_signup_block_form');
      break;
  }
  return $block;
}

/**
 * Builds email submission form.
 */
function convio_signup_block_form($form, &$form_state) {
  $form = array();

  $form['constituent_email_address'] = array(
    '#type' => 'textfield',
    '#description' => t('Enter your email address to stay in touch.'),
    '#required' => TRUE,
    '#maxlength' => 254,
    '#size' => 14,
    '#attributes' => array('placeholder' => variable_get('convio_signup_default_placeholder', t(DEFAULT_PLACEHOLDER_TEXT))),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Validates user input.
 */
function convio_signup_block_form_validate($form, &$form_state) {
  $constituent_email_address = $form_state['values']['constituent_email_address'];
  if (!valid_email_address($constituent_email_address)) {
    form_set_error('constituent_email_address', "You've entered an invalid email address");
  }
}

/**
 * Adds email address to CLO database via form submission.
 */
function convio_signup_block_form_submit($form, &$form_state) {
}


/**
 * Implements hook_help().
 */
function convio_signup_help($path, $arg) {
  switch ($path) {
    case 'admin/help#convio_signup':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("This module makes a new block available for admins to include on other pages. The block contains a simple form which will add an email address to the constituent database in Blackbaud's Convio Luminate Online product") . '</p>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function convio_signup_permission() {
  return array(
    'administer convio signup' => array(
      'title' => t('Administer Convio Signup'),
      'description' => t('Perform administrative tasks on Convio Signup functionality.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function convio_signup_menu() {
  $items = array();

  // Admin configuration group.
  $items['admin/config/convio_signup'] = array(
    'title' => 'Convio Signup',
    'description' => 'Administer Convio Signup',
    'access arguments' => array('administer convio signup'),
  );

  // Admin configuration - Settings.
  $items['admin/config/convio_signup/manage'] = array(
    'title' => 'Convio Signup Settings',
    'description' => 'Manage Convio Signup settings and configurations.',
    'access arguments' => array('administer convio signup'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('convio_signup_admin_settings_form'),
  );

  return $items;
}

/**
 * Creates Convio Signup administration form.
 */
function convio_signup_admin_settings_form($node, &$form_state) {
  $form = array();

  $form['overview'] = array(
    '#markup' => t('This interface allows administrators to manage general Convio Email settings.'),
  );

  $form['convio_signup_clo_form_id'] = array(
    '#title' => t('Convio Luminate Online Survey ID'),
    '#description' => t('The 4-digit survey ID used by Convio to identify the survey.'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#size' => 4,
    '#maxlength' => 4,
  );

  $form['convio_signup_clo_email_field_placeholder'] = array(
    '#title' => t('Email field placeholder'),
    '#description' => t("The text that displays inside the email field before the user enters their email address. Defaults to '") . DEFAULT_PLACEHOLDER_TEXT . t("'."),
    '#type' => 'textfield',
    '#default_value' => variable_get('convio_signup_default_placeholder', t(DEFAULT_PLACEHOLDER_TEXT)),
    '#size' => 30,
    '#maxlength' => 512,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

/**
 * Validates Convio Signup admin configuration form.
 */
function convio_signup_admin_settings_form_validate($form, &$form_state) {
  $clo_form_id = intval($form_state['values']['convio_signup_clo_form_id']);
  if ($clo_form_id < 1000 || $clo_form_id > 9999) {
    form_set_error('convio_signup_clo_form_id', t('The Convio Luminate Online Survey ID must be a 4 digit number.'));
  }
}

/**
 * Action to take upon submission of the Convio Signup admin configuration form.
 */
function convio_signup_admin_settings_form_submit($form, &$form_state) {
  variable_set('convio_signup_default_placeholder', $form_state['values']['convio_signup_clo_email_field_placeholder']);
  drupal_set_message(t('Your configuration has been saved.'));
}
